server:
  port: 8080

# ?? ?? ?? ??? ?? ??? ?? ??? ???????.(?? han ??? ???????.)
spring:
  profiles:
    active:
      - ${ACTIVE_LOCAL_PROFILE}     #Run -> Edit Configuration -> Modify Options -> Environment Variables ??
