server:
  port: ${PORT:8080}

# ?? ?? ?? ??? ?? ??? ?? ??? ???????.(?? han ??? ???????.)
spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active:
      - ${ACTIVE_LOCAL_PROFILE}     #Run -> Edit Configuration -> Modify Options -> Environment Variables ??
