version: "3.8"

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hannoi/kwu-swe-repository
    ports:
      - "8080:8080"
    environment:
      ACTIVE_LOCAL_PROFILE: prod
    env_file:
      - ./build/.env
